First iteration of the Database API
jkutkutOrg/Android-CineHub pull request #28
Opened 2023-03-10 19:25 UTC by Jkutkut

First iteration of the DB API.

Note: The issue #19 will be kept open to continue working on new features.

2023-03-10 19:29 UTC, alexeses approved these changes
The implemented methods seem to be fine! I will add more methods to the issue as I need them 🎉.

2023-03-10 19:57 UTC, alexaib2002 requested changes
Everything looks very promising, but interfaces with one method intended to be used as lambda expressions should have the `@FunctionalInterface` annotation on top of the interface declaration!

Also, I would like to point out that making changes on `MainActivity` doesn't seem necessary, as this is an API, all testing could be done with the `ExampleUnitTest` class. Making changes on a deleted file of another branches may end up on merging conflicts. Still, I will approve this, as `MainActivity` can be deleted on the merging process.

Summarizing, I think the only things that must be changed are the `FunctionalInterface` ones. Good work!

2023-03-10 19:57 UTC, alexaib2002 commented on app/CineHub/app/src/main/java/org/cinehub/api/result/OnFailureCallback.java
> +public interface OnFailureCallback<T> {
As this interface is meant to be used as a lambda expression, it should have a `@FunctionalInterface` annotation on top of the declaration

2023-03-10 19:57 UTC, alexaib2002 commented on app/CineHub/app/src/main/java/org/cinehub/api/result/OnSuccessCallback.java
> +public interface OnSuccessCallback {
Same as OnFailureCallback, it should have the `@FunctionalInterface` annotation

2023-03-10 19:57 UTC, alexaib2002 commented on app/CineHub/app/src/main/java/org/cinehub/api/result/OnSuccessValueCallback.java
> +public interface OnSuccessValueCallback<T> {
Same as OnFailureCallback, it should have the @FunctionalInterface annotation

2023-03-10 23:05 UTC, alexaib2002 commented
@Jkutkut, on second thought I think the Callback interfaces may not even be necessary: Both `OnFailureCallback` and `OnSuccessValueCallback` can be replaced with the builtin `Callable<T>` Java interface. As for the `OnSuccessCallback`, it could be replaced with `Runnable`.

This would simplify the API class structure, but code may be more difficult to read on the long run. The choice is up to you!

2023-03-11 11:14 UTC, Jkutkut commented
@alexaib2002 
- @FunctionalInterface: Sure, it will be implemented now.
- ExampleUnitTest: I strongly agree. Furthermore, I was already working on it. However, I met an error: Firebase requests the context of the current activity to work. I am working on a way to test these methods using `InstrumentalTests`, where an applicaction context is generated and the test ir run on the device. However, due to the urgency of deploying a first iteration of the API, I prioritized the logic using the main activity as a tool for testing. This should not be a problem anyway because this activity does not exists in the UI/UX development branches (and will be removed, as you mentioned).
- Runnable and Callable: It was one of the options I had but I found the same issue as you mentioned: readability. For this reason, I will continue using this custom interfaces.

2023-03-11 11:22 UTC, alexaib2002 approved these changes
All issues solved, changes approved. Unit testing can be implemented on future revisions of #19

2023-03-11 11:41 UTC, merged